security:

    encoders:
        'Symfony\Component\Security\Core\User\User': plaintext

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: 'user',  roles: [ROLE_USER]  }
                    admin: { password: 'admin', roles: [ROLE_ADMIN] }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:    '^/'
            anonymous:  true
            #http_basic: { provider: in_memory     }
            logout:     { path: logout, target: / }
            form_login:
                provider:    in_memory
                login_path:  login
                check_path:  login

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/,      role: ROLE_USER }
